# Generated by Django 5.0.3 on 2024-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image_name',
            field=models.CharField(default='one.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
